name: Publish

concurrency:
  group: snjs
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  lint:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn lint

  unit-tests:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --immutable # required for microtime package in @standardnotes/time
      - run: yarn build
      - run: yarn test:unit

  e2e-tests:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn test:e2e

  publish:
    if: contains(github.event.head_commit.message, 'chore(release)') == false
    needs: [ lint, unit-tests, e2e-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn build
      - name: Setup git config
        run: |
          git config --global user.name "standardci"
          git config --global user.email "ci@standardnotes.com"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - run: yarn version-bump
      - run: yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-app-repo:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Notify App Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          repository: standardnotes/app
          event-type: snjs-updated-event

  update-server-repo:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Notify App Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          repository: standardnotes/server
          event-type: snjs-updated-event

  git-sync:
    needs: [ publish, update-app-repo, update-server-repo ]
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "standardnotes/snjs"
          source_branch: "refs/remotes/source/*"
          destination_repo: "standardnotes/private-snjs"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  notify_discord:
    needs: [ publish, update-app-repo, update-server-repo ]
    if: contains(github.event.head_commit.message, 'chore(release)') == false

    runs-on: ubuntu-latest

    steps:
    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        censor_username: false
